import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { AlertCircle, Mail, ArrowRight, Lock } from "lucide-react";
import { Helmet } from "react-helmet";
import { Link } from "react-router-dom";

const Disclaimer = () => {
  return (
    <>
      <Helmet>
        <title>Disclaimer | Hi Honey</title>
        <meta
          name="description"
          content="Read the disclaimer for using Hi Honey spin wheel tool. Understand the limitations, responsibilities, and proper use of our random selection service."
        />
        <link rel="canonical" href="https://hihoney.site/disclaimer" />
      </Helmet>

      <article className="container mx-auto px-4 py-8 md:py-12 max-w-5xl">
        <div className="text-center mb-8 md:mb-12">
          <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-gray-900 dark:text-white">
            Disclaimer
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground">
            Please read this disclaimer carefully before using Hi Honey
          </p>
        </div>

        <Card className="p-6 md:p-8 lg:p-10 space-y-8">
          <div className="bg-primary/5 border border-primary/20 rounded-lg p-6">
            <p className="text-base md:text-lg text-foreground font-medium">
              By accessing and using this Website, you accept and agree to be
              bound by the terms and conditions outlined in this disclaimer.
            </p>
          </div>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              General Information
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              The information and tools provided on Hi Honey are for
              entertainment and decision-making assistance purposes only. While
              we strive to provide a reliable and accurate service, the Website
              is provided on an "as is" and "as available" basis without any
              warranties of any kind.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              No Professional Advice
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Hi Honey is a random selection tool designed for entertainment and
              general decision-making purposes. The results generated by our
              wheel spinner should not be considered as:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>• Professional advice of any kind</li>
              <li>• Legal, financial, or medical guidance</li>
              <li>• Binding decisions or commitments</li>
              <li>• Guarantees of outcomes or results</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              Users should exercise their own judgment and discretion when
              making important decisions. For matters requiring professional
              expertise, please consult qualified professionals in the relevant
              field.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Randomness and Fairness
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              While we implement algorithms designed to generate random results,
              we make no guarantees regarding:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>• The absolute randomness of every spin</li>
              <li>• Specific outcomes or results</li>
              <li>• The suitability of results for any particular purpose</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              Users acknowledge that random selection tools are meant to assist
              with decision-making but should not be the sole basis for critical
              or life-changing decisions.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              User Responsibility
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Users are solely responsible for:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>• How they choose to use the Website and its results</li>
              <li>• Any decisions made based on wheel spin outcomes</li>
              <li>
                • Verifying the appropriateness of using a random selection tool
                for their specific needs
              </li>
              <li>
                • Ensuring compliance with any applicable laws or regulations in
                their jurisdiction
              </li>
              <li>• The content they input into the wheel spinner</li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              No Liability for Decisions
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Hi Honey and its operators shall not be held liable for:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>• Any decisions made based on wheel spin results</li>
              <li>• Any consequences arising from the use of our service</li>
              <li>
                • Disputes arising from the use of our tool for contests,
                giveaways, or selections
              </li>
              <li>
                • Any direct, indirect, incidental, consequential, or punitive
                damages
              </li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Third-Party Use
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              If you use Hi Honey for contests, giveaways, team selections, or
              any purpose involving third parties:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>
                • You are responsible for ensuring fair use and compliance with
                applicable rules
              </li>
              <li>
                • You must clearly communicate to participants how the tool will
                be used
              </li>
              <li>
                • You assume all liability for disputes or issues arising from
                such use
              </li>
              <li>
                • We are not responsible for mediating or resolving any
                conflicts
              </li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Technical Limitations
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Hi Honey relies on technology and internet connectivity. We do not
              guarantee:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>• Uninterrupted or error-free service</li>
              <li>• That the Website will be available at all times</li>
              <li>• That all features will work on all devices or browsers</li>
              <li>
                • That data entered will be permanently stored or retrievable
              </li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              We recommend users take screenshots or note important results, as
              we do not guarantee data persistence.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              No Gambling or Illegal Use
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Hi Honey is not intended for:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>• Gambling or betting purposes</li>
              <li>• Any illegal activities</li>
              <li>
                • Making selections in violation of local laws or regulations
              </li>
              <li>• Any use that would violate the rights of others</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              Users must ensure their use of the Website complies with all
              applicable laws in their jurisdiction.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              External Links
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Our Website may contain links to third-party websites or services.
              We are not responsible for:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>
                • The content, accuracy, or practices of external websites
              </li>
              <li>
                • Any damages or losses arising from visiting linked websites
              </li>
              <li>• Privacy policies of external sites</li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Changes and Updates
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              We reserve the right to:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>
                • Modify or discontinue the Website or any features at any time
              </li>
              <li>• Update this disclaimer without prior notice</li>
              <li>• Change our service terms and conditions</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              Continued use of the Website after changes constitutes acceptance
              of those changes.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Intellectual Property
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              All content, design, graphics, and features of Hi Honey are
              provided for your use on the Website only. Unauthorized
              reproduction, distribution, or commercial use is prohibited.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Accuracy of Information
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              While we make reasonable efforts to ensure accuracy, we do not
              warrant:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>
                • The completeness or reliability of any information on the
                Website
              </li>
              <li>• That errors will be corrected promptly</li>
              <li>• The accuracy of any automated results or calculations</li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Children's Use
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Parents and guardians are responsible for monitoring their
              children's use of Hi Honey. We recommend parental supervision for
              users under the age of 13.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Limitation of Liability
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              To the fullest extent permitted by law, Hi Honey, its operators,
              and affiliates shall not be liable for any damages whatsoever,
              including but not limited to:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>• Loss of data or information</li>
              <li>• Loss of profits or business opportunities</li>
              <li>• Service interruptions or technical failures</li>
              <li>• Any claims arising from your use of the Website</li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Indemnification
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              You agree to indemnify and hold harmless Hi Honey, its operators,
              and affiliates from any claims, damages, losses, or expenses
              arising from:
            </p>
            <ul className="space-y-2 text-muted-foreground pl-6">
              <li>• Your use of the Website</li>
              <li>• Your violation of these terms</li>
              <li>• Your violation of any rights of others</li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Jurisdiction
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              This disclaimer shall be governed by and construed in accordance
              with applicable laws. Any disputes shall be subject to the
              exclusive jurisdiction of the appropriate courts.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Severability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              If any provision of this disclaimer is found to be unenforceable
              or invalid, that provision shall be limited or eliminated to the
              minimum extent necessary, and the remaining provisions shall
              remain in full force and effect.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Contact Us
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              If you have any questions or concerns about this disclaimer,
              please contact us:
            </p>
            <div className="flex items-center gap-2 text-foreground">
              <Mail className="h-5 w-5 text-primary" />
              <span className="font-medium">Email:</span>
              <a
                href="mailto:chaudhrayadam@gmail.com"
                className="text-primary hover:underline font-semibold"
              >
                chaudhrayadam@gmail.com
              </a>
            </div>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">
              Acknowledgment
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              By using Hi Honey, you acknowledge that you have read, understood,
              and agree to be bound by this disclaimer.
            </p>
            <div className="bg-primary/10 border-l-4 border-primary rounded-r-lg p-6 mt-6">
              <p className="text-lg font-semibold text-foreground">
                Remember: Hi Honey is a fun tool to help with everyday
                decisions. Use it wisely, responsibly, and enjoy the spin!
              </p>
            </div>
          </section>
        </Card>

        {/* Next Step Navigation */}
        <Card className="p-6 md:p-8 bg-gradient-to-r from-primary/5 via-primary/10 to-primary/5 border-2 border-primary/20 mt-8">
          <div className="text-center mb-4">
            <h3 className="text-xl md:text-2xl font-bold mb-2">
              Your Privacy Matters
            </h3>
            <p className="text-muted-foreground">
              Learn how we protect your data and respect your privacy
            </p>
          </div>
          <Link
            to="/privacy"
            className="flex items-center justify-center gap-2 bg-primary text-primary-foreground px-6 py-3 rounded-lg font-semibold hover:bg-primary/90 transition-all duration-300 transform hover:scale-105 shadow-lg hover:shadow-xl mx-auto max-w-sm"
          >
            <Lock className="h-5 w-5" />
            <span>Privacy Policy</span>
            <ArrowRight className="h-5 w-5" />
          </Link>
        </Card>
      </article>
    </>
  );
};

export default Disclaimer;
