import { Card } from "@/components/ui/card";
import { Helmet } from "react-helmet";
import { ArrowRight, FileText } from "lucide-react";
import { Link } from "react-router-dom";

const Disclaimer = () => {
  return (
    <>
      <Helmet>
        <title>Disclaimer - Online Spin Wheel</title>
        <meta
          name="description"
          content="Disclaimer for Online Spin Wheel (onlinespinwheel.fun), operated by Auroxa Tech: informational and entertainment use only, as-is service, ads, external links, liability limits, and contact."
        />
        <link rel="canonical" href="https://onlinespinwheel.fun/disclaimer" />
      </Helmet>

      <article className="container mx-auto px-4 py-8 md:py-12 max-w-5xl">
        <div className="text-center mb-8 md:mb-12">
          <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold mb-4 text-gray-900 dark:text-white">
            Disclaimer
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground">
            Important limitations on use of our site and tools
          </p>
        </div>

        <Card className="p-6 md:p-8 lg:p-10 mb-6 md:mb-8 space-y-8">
          <section>
            <p className="text-muted-foreground leading-relaxed mb-4">
              The information and tools provided by Online Spin Wheel
              (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), operated by Auroxa Tech, on{" "}
              <a
                href="https://onlinespinwheel.fun"
                className="text-primary hover:underline font-medium break-all"
              >
                https://onlinespinwheel.fun
              </a>{" "}
              are for general informational, educational and entertainment purposes
              only. All information and services on the Site are provided in good
              faith. However, we make no representation or warranty of any kind,
              express or implied, regarding the accuracy, adequacy, validity,
              reliability, availability or completeness of any tool or information on
              the site.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              &quot;As-Is&quot; and Entertainment Purpose Only
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Online Spin Wheel is designed as a fun, interactive decision-making
              tool. While we use advanced, cryptographically secure algorithms to
              ensure the wheel is mathematically fair, the service is provided on an
              &quot;as-is&quot; and &quot;as-available&quot; basis.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-4">
              The wheel is strictly intended for low-stakes, everyday choices (e.g.,
              classroom activities, social media giveaways or game nights). We
              strongly advise against using this tool for high-stakes, legally
              binding or financial decisions.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              You acknowledge that any reliance on the results generated by the wheel
              is entirely at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Advertising and Ad-Network Disclaimer
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              To keep our tool 100% free for all users worldwide, Online Spin Wheel is
              an ad-supported platform.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-4">
              We partner with third-party advertising networks, including Google
              AdSense and Ezoic (Google AdX), to display programmatic advertisements
              on our site. Please note:
            </p>
            <ul className="space-y-3 text-muted-foreground ml-1">
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  The presence of any advertisement on our site does not constitute an
                  endorsement, guarantee or recommendation by Auroxa Tech of the
                  product, service or company being advertised.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  We have no direct control over the specific ads that are served to
                  you, as they are dynamically generated by our advertising partners
                  based on your browsing habits and cookies.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  Any interactions, purchases or engagements you have with third-party
                  advertisers found on our site are solely between you and the
                  advertiser.
                </span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              External Links Disclaimer
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Our site may contain (or you may be sent through the site to) links to
              other websites, third-party content or banners/advertisements belonging
              to third parties. Such external links are not investigated, monitored or
              checked for accuracy, adequacy, validity, reliability, availability or
              completeness by us.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-4">
              We do not warrant, endorse, guarantee or assume responsibility for the
              accuracy or reliability of any information offered by third-party
              websites linked through the site. We will not be a party to or in any way
              be responsible for monitoring any transaction between you and
              third-party providers of products or services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Limitation of Liability
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Under no circumstance shall Auroxa Tech, its founders, employees or
              affiliates have any liability to you for any loss or damage of any kind
              incurred as a result of the use of the Site, the reliance on any
              information provided on the site or the outcomes decided by the spin
              wheel tool.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Your use of the Site and your reliance on any feature or result generated
              by the site is solely at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Fair Use and User Responsibility
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Online Spin Wheel does not store the data you input into the wheel on our
              servers, all processing is handled locally within your browser. Users
              are solely responsible for the content, names and data they choose to
              input into the wheel.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              We are not liable for any disputes, arguments or conflicts that arise
              between users or third parties based on the results generated by our
              tool.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">Contact Us</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              If you have any questions or concerns regarding this Disclaimer, please
              contact us at:
            </p>
            <ul className="space-y-3 text-muted-foreground ml-1">
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">Email:</strong>{" "}
                  <a
                    href="mailto:onlinespinwheel@gmail.com"
                    className="text-primary hover:underline font-semibold"
                  >
                    onlinespinwheel@gmail.com
                  </a>
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">Website:</strong>{" "}
                  <a
                    href="https://onlinespinwheel.fun"
                    className="text-primary hover:underline break-all"
                  >
                    https://onlinespinwheel.fun
                  </a>
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">Operated by:</strong> Auroxa
                  Tech
                </span>
              </li>
            </ul>
          </section>
        </Card>

        <Card className="p-6 md:p-8 bg-gradient-to-r from-primary/5 via-primary/10 to-primary/5 border-2 border-primary/20 mt-8">
          <div className="text-center mb-4">
            <h3 className="text-xl md:text-2xl font-bold mb-2">Related policies</h3>
            <p className="text-muted-foreground">
              See our Terms &amp; Conditions and Privacy Policy for more detail
            </p>
          </div>
          <div className="flex flex-col sm:flex-row gap-3 justify-center items-stretch sm:items-center max-w-lg mx-auto">
            <Link
              to="/terms-and-conditions"
              className="flex items-center justify-center gap-2 bg-primary text-primary-foreground px-6 py-3 rounded-lg font-semibold hover:bg-primary/90 transition-all"
            >
              <FileText className="h-5 w-5" />
              <span>Terms &amp; Conditions</span>
              <ArrowRight className="h-5 w-5" />
            </Link>
            <Link
              to="/privacy-policy"
              className="flex items-center justify-center gap-2 border-2 border-primary text-primary px-6 py-3 rounded-lg font-semibold hover:bg-primary/10 transition-all"
            >
              <FileText className="h-5 w-5" />
              <span>Privacy Policy</span>
              <ArrowRight className="h-5 w-5" />
            </Link>
          </div>
        </Card>
      </article>
    </>
  );
};

export default Disclaimer;
