import { Card } from "@/components/ui/card";
import { Helmet } from "react-helmet";
import { FileText, ArrowRight, Shield } from "lucide-react";
import { Link } from "react-router-dom";

const Terms = () => {
  return (
    <>
      <Helmet>
        <title>Terms and Conditions - Online Spin Wheel</title>
        <meta
          name="description"
          content="Terms and Conditions for Online Spin Wheel (onlinespinwheel.fun), operated by Auroxa Tech: use of the service, ads, eligibility, randomness, IP, liability, governing law, and contact."
        />
        <link rel="canonical" href="https://onlinespinwheel.fun/terms" />
      </Helmet>

      <article className="container mx-auto px-4 py-8 md:py-12 max-w-5xl">
        <div className="text-center mb-8 md:mb-12">
          <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 dark:text-white">
            Terms and Conditions
          </h1>
        </div>

        <Card className="p-6 md:p-8 lg:p-10 mb-6 md:mb-8 space-y-8">
          <section>
            <p className="text-muted-foreground leading-relaxed mb-4">
              These Terms and Conditions (&quot;Terms&quot;) govern your use of the Online
              Spin Wheel website and tool at{" "}
              <a
                href="https://onlinespinwheel.fun"
                className="text-primary hover:underline font-medium break-all"
              >
                https://onlinespinwheel.fun
              </a>{" "}
              (the &quot;Site&quot; and &quot;Service&quot;). The Site is owned and operated by Auroxa
              Tech (&quot;we&quot;, &quot;us&quot; or &quot;our&quot;).
            </p>
            <p className="text-muted-foreground leading-relaxed mb-4">
              By accessing or using the site, you agree to be bound by these Terms.
              If you do not agree to these Terms, you must not use this website.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              About the Service
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Online Spin Wheel provides a free, browser-based random picker that
              allows users to add names, numbers or options to a virtual wheel and
              spin to generate a random selection. The Service is provided for
              entertainment, educational, organizational and general decision-making
              support.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Ad-Supported Model
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Our Service is provided 100% free of charge. To maintain this free
              access, the site is ad-supported. By using the site, you acknowledge
              and agree that we may display third-party advertisements (such as
              Google AdSense and Ezoic) generated by programmatic networks. Your
              interaction with these ads is subject to our{" "}
              <Link to="/privacy" className="text-primary hover:underline font-medium">
                Privacy Policy
              </Link>{" "}
              and{" "}
              <Link
                to="/cookie-policy"
                className="text-primary hover:underline font-medium"
              >
                Cookie Policy
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Eligibility and Acceptable Use
            </h2>
            <ul className="space-y-3 text-muted-foreground ml-1">
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">Age Requirement:</strong> You
                  must be at least 13 years old (or the minimum age required by your
                  country&apos;s laws) to use the site without supervision. If you are
                  a minor, you should use the Site under the supervision of a parent,
                  teacher or legal guardian.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">Lawful Use:</strong> You agree
                  not to use the Site for any unlawful purpose. You must not submit
                  content into the wheel that is illegal, harmful, abusive, hateful or
                  otherwise inappropriate.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">No Interference:</strong> You
                  agree not to attempt to interfere with the normal operation,
                  security or performance of the Site, including by hacking, scraping,
                  distributing malware or reverse-engineering our code.
                </span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Randomness and Decision-Making
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              We pride ourselves on fairness. Online Spin Wheel utilizes advanced,
              cryptographically secure seeds to simulate true randomness and
              real-world physics. However, please note:
            </p>
            <ul className="space-y-3 text-muted-foreground ml-1 mb-4">
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  The Service is provided &quot;as is&quot;. While we strive for absolute
                  mathematical fairness, we do not guarantee its suitability for
                  high-stakes, legally binding or financial decisions.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  You are solely responsible for how you use the results produced by
                  the wheel. Online Spin Wheel and Auroxa Tech are not responsible or
                  liable for any disputes, arguments or outcomes arising from decisions
                  made using our Service.
                </span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              No Accounts and User Content
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Online Spin Wheel does not require a user account. Any text, names or
              numbers you enter into the wheel are processed locally in your browser
              and are your sole responsibility. We strongly advise against entering
              sensitive personal or financial information into the wheel.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              If you send us feedback, suggestions or bug reports via email, you grant
              Auroxa Tech a non-exclusive, worldwide, royalty-free license to use that
              feedback to improve the Service without any obligation or compensation to
              you.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Intellectual Property
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Unless stated otherwise, all content on the site - including the wheel
              interface, design, text, graphics, logos, physics engine and underlying
              code - is owned by Auroxa Tech and is protected by applicable copyright,
              trademark and intellectual property laws.
            </p>
            <ul className="space-y-3 text-muted-foreground ml-1">
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">Restrictions:</strong> You may
                  not copy, modify, distribute, sell, or lease any part of the Site or
                  its underlying code. You may not use our brand name or logos without
                  prior written permission.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">Permitted Use:</strong> You are
                  fully permitted (and encouraged!) to display the Site on your own
                  devices, share screen recordings, or live-stream the wheel as part of
                  your normal use.
                </span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Third-Party Services and Links
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              The Site may contain links to third-party websites, tools, or
              advertisements that are not owned or controlled by us. We are not
              responsible for the content, privacy policies or practices of any
              third-party sites. You access them entirely at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Disclaimer of Warranties
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              The Site and Service are provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot;
              basis, without warranties of any kind, whether express or implied.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              To the fullest extent permitted by law, Auroxa Tech disclaims all
              warranties, including but not limited to implied warranties of
              merchantability, fitness for a particular purpose and non-infringement.
              We do not warrant that the Site will be completely error-free, 100%
              secure or available at all times without disruption.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Limitation of Liability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by applicable law, Auroxa Tech, its
              founders and its team will not be liable for any indirect, incidental,
              special, consequential or punitive damages or any loss of profits,
              data, or goodwill, arising out of or in connection with your use of the
              site or these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">Indemnification</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree to defend, indemnify and hold harmless Online Spin Wheel and
              Auroxa Tech from and against any claims, damages, liabilities, losses
              and expenses (including reasonable legal fees) arising out of or related
              to your use of the Service or your violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Governing Law and Jurisdiction
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms are governed by and construed in accordance with the laws
              of Pakistan, without regard to its conflict of law rules. Any disputes
              arising out of or relating to these Terms or your use of the site will
              be resolved exclusively in the courts of Rawalpindi, Pakistan.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Changes to These Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to update or modify these Terms at any time without
              prior notice. When we do, we will update the &quot;Effective Date&quot; at the top
              of this page. Your continued use of the site after any changes take
              effect constitutes your binding acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">Contact Us</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              If you have any questions or concerns about these Terms and Conditions,
              please contact us at:
            </p>
            <ul className="space-y-3 text-muted-foreground ml-1">
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">Email:</strong>{" "}
                  <a
                    href="mailto:onlinespinwheel@gmail.com"
                    className="text-primary hover:underline font-semibold"
                  >
                    onlinespinwheel@gmail.com
                  </a>
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">Website:</strong>{" "}
                  <a
                    href="https://onlinespinwheel.fun"
                    className="text-primary hover:underline break-all"
                  >
                    https://onlinespinwheel.fun
                  </a>
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1.5 flex-shrink-0">●</span>
                <span>
                  <strong className="text-foreground">Operated by:</strong> Auroxa
                  Tech
                </span>
              </li>
            </ul>
          </section>
        </Card>

        <Card className="p-6 md:p-8 bg-gradient-to-r from-primary/5 via-primary/10 to-primary/5 border-2 border-primary/20 mt-8">
          <div className="text-center mb-4">
            <h3 className="text-xl md:text-2xl font-bold mb-2">Related policies</h3>
            <p className="text-muted-foreground">
              Privacy, cookies, and disclaimer
            </p>
          </div>
          <div className="flex flex-col sm:flex-row flex-wrap gap-3 justify-center items-stretch max-w-2xl mx-auto">
            <Link
              to="/privacy"
              className="flex items-center justify-center gap-2 bg-primary text-primary-foreground px-6 py-3 rounded-lg font-semibold hover:bg-primary/90 transition-all"
            >
              <Shield className="h-5 w-5" />
              <span>Privacy Policy</span>
              <ArrowRight className="h-5 w-5" />
            </Link>
            <Link
              to="/cookie-policy"
              className="flex items-center justify-center gap-2 border-2 border-primary text-primary px-6 py-3 rounded-lg font-semibold hover:bg-primary/10 transition-all"
            >
              <FileText className="h-5 w-5" />
              <span>Cookie Policy</span>
            </Link>
            <Link
              to="/disclaimer"
              className="flex items-center justify-center gap-2 border-2 border-primary text-primary px-6 py-3 rounded-lg font-semibold hover:bg-primary/10 transition-all"
            >
              <FileText className="h-5 w-5" />
              <span>Disclaimer</span>
            </Link>
          </div>
        </Card>
      </article>
    </>
  );
};

export default Terms;
